name: ${project.artifactId}
main: com.mcmiddleearth.connect.ConnectPlugin
version: ${project.version}
description: Connecting MCME servers in a BungeeCord
load: POSTWORLD
api-version: 1.15
softdepend: [PremiumVanish, DiscordSRV]

commands:
    restart:
        description: manages server restarts across the network
        usage: /restart <server>|proxy|all|reloadconfig|cancel
        aliases: reboot
    stop:
        description: stops a server
        usage: /stop [shutdown message]
        aliases: shutdown
permissions:
    mcmeconnect.tp:
        description: allows to tp to other players across the network
        default: op
    mcmeconnect.tp.other:
        description: allows to tp other players across the network
        default: op
        children:
            mcmeconnect.tp: true
    mcmeconnect.tphere:
        description: allows to use /tphere across the network
        default: op
    mcmeconnect.world:
        description: subnodes like mcmeconnect.world.moria allow to access that server
        default: op
    mcmeconnect.watchdog:
        description: displays warnings in case of a server being down
        default: op
    mcmeconnect.ignoreDisabledMVTP:
        description: allows to use /mvtp or /world in protected new player area
        default: op
    mcmeconnect.restart:
        description: allows to restarts servers
        default: op
